### ISSUE TITLE
link to image is broken

### ISSUE THREAD

**Issue by Finkregh** [algorys/gitlabproject#2]
the link to the gitlab-logo is broken, as it uses a relative link:
```html
<img src="lib/plugins/gitlabproject/images/gitlab.png" class="gitlab">
```

**Comment by algorys** [comment]
Ok, I'll have a look ASAP

**Comment by algorys** [comment]
Strange, because normally this link should be work...

When you try to reach `http://WIKI_URL/lib/plugins/gitlabproject/images/gitlab.png`, image is not displayed ?

Because, it's working very well on my test server and for other plugins. Check you have `gitlab.png` in gitlab plugin folder also.

**Comment by Finkregh** [comment]
yep, but when i open /some/other/page then i get a relative link to 'lib/plugins/...'

**Comment by algorys** [comment]
@Finkregh Sorry, but I don't undestand what you say with `/some/other/page` ? Have you a screenshot please to understand your problem ?

**Comment by Finkregh** [comment]
no problem ;-)

i open the wiki page via `https://wiki/playground/playground`.
the image there is linked via `src="lib/plugins/...` and it should be linked via `src="https://wiki/lib/plugins/...`

**Comment by algorys** [comment]
Yes but normally Dokuwiki add the rest of url alone.... maybe it's due to https.

I'll try to find a way to add Wiki url to this link.

@Finkregh when you open deleoper tools in your browser and you hover the link, what url you have ?

**Comment by algorys** [comment]
@Finkregh last version should solve your problem :wink:

**Comment by Finkregh** [comment]
yes, but i cant update via the DW gui because you changed things in the devel-branch...

**Comment by algorys** [comment]
@Finkregh oups sorry, I merge right now.

**Edit:** you can now update plugin.

**Comment by Finkregh** [comment]
in line 153 is another image-link :-)

**Comment by algorys** [comment]
Sorry, I forget this case. Done.
